create table vehicle (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	make VARCHAR(50) NOT NULL,
	model VARCHAR(50) NOT NULL,
	price NUMERIC(50) NOT NULL
);
insert into vehicle (id, make, model, price) values (1, 'Pontiac', 'Firebird', 54634);
insert into vehicle (id, make, model, price) values (2, 'Audi', 'A3', 67797);
insert into vehicle (id, make, model, price) values (3, 'Chrysler', 'Crossfire', 57571);
insert into vehicle (id, make, model, price) values (4, 'Mercedes-Benz', 'C-Class', 24820);
insert into vehicle (id, make, model, price) values (5, 'Isuzu', 'Ascender', 21038);
insert into vehicle (id, make, model, price) values (6, 'Ford', 'Fusion', 70539);
insert into vehicle (id, make, model, price) values (7, 'GMC', 'Vandura G2500', 86985);
insert into vehicle (id, make, model, price) values (8, 'Jaguar', 'XK Series', 11761);
insert into vehicle (id, make, model, price) values (9, 'Ford', 'Taurus', 45360);
insert into vehicle (id, make, model, price) values (10, 'Saturn', 'VUE', 77975);
insert into vehicle (id, make, model, price) values (11, 'Mazda', 'Navajo', 14324);
insert into vehicle (id, make, model, price) values (12, 'Subaru', 'Alcyone SVX', 63299);
insert into vehicle (id, make, model, price) values (13, 'Volkswagen', 'GTI', 32017);
insert into vehicle (id, make, model, price) values (14, 'Mitsubishi', 'Mighty Max', 55983);
insert into vehicle (id, make, model, price) values (15, 'Chevrolet', 'Tahoe', 60471);
insert into vehicle (id, make, model, price) values (16, 'Honda', 'Civic', 88378);
insert into vehicle (id, make, model, price) values (17, 'Ford', 'Club Wagon', 70510);
insert into vehicle (id, make, model, price) values (18, 'Toyota', 'Tacoma', 98824);
insert into vehicle (id, make, model, price) values (19, 'Ford', 'E150', 22765);
insert into vehicle (id, make, model, price) values (20, 'Volkswagen', 'Eurovan', 90255);
insert into vehicle (id, make, model, price) values (21, 'Ford', 'F150', 72352);
insert into vehicle (id, make, model, price) values (22, 'Cadillac', 'DTS', 51445);
insert into vehicle (id, make, model, price) values (23, 'Nissan', 'Titan', 74423);
insert into vehicle (id, make, model, price) values (24, 'Ram', '1500', 33657);
insert into vehicle (id, make, model, price) values (25, 'Mercedes-Benz', 'CLK-Class', 34869);
insert into vehicle (id, make, model, price) values (26, 'Toyota', 'Yaris', 49853);
insert into vehicle (id, make, model, price) values (27, 'Honda', 'Accord', 40480);
insert into vehicle (id, make, model, price) values (28, 'Dodge', 'Dakota', 42799);
insert into vehicle (id, make, model, price) values (29, 'Audi', 'A4', 19920);
insert into vehicle (id, make, model, price) values (30, 'Honda', 'CR-Z', 58992);
insert into vehicle (id, make, model, price) values (31, 'Honda', 'Element', 79961);
insert into vehicle (id, make, model, price) values (32, 'Geo', 'Metro', 38052);
insert into vehicle (id, make, model, price) values (33, 'Mazda', 'Mazda6', 64401);
insert into vehicle (id, make, model, price) values (34, 'Volvo', '940', 14571);
insert into vehicle (id, make, model, price) values (35, 'GMC', 'Sonoma', 61234);
insert into vehicle (id, make, model, price) values (36, 'BMW', 'M', 20966);
insert into vehicle (id, make, model, price) values (37, 'Subaru', 'Outback', 21640);
insert into vehicle (id, make, model, price) values (38, 'Toyota', 'Supra', 85809);
insert into vehicle (id, make, model, price) values (39, 'GMC', 'Savana 3500', 79144);
insert into vehicle (id, make, model, price) values (40, 'Mitsubishi', 'Pajero', 84425);
insert into vehicle (id, make, model, price) values (41, 'Mazda', 'MPV', 47703);
insert into vehicle (id, make, model, price) values (42, 'Chevrolet', 'Suburban 2500', 84420);
insert into vehicle (id, make, model, price) values (43, 'Toyota', '4Runner', 88559);
insert into vehicle (id, make, model, price) values (44, 'Chevrolet', 'Express 2500', 57436);
insert into vehicle (id, make, model, price) values (45, 'Chevrolet', 'Monte Carlo', 87889);
insert into vehicle (id, make, model, price) values (46, 'Porsche', '968', 47671);
insert into vehicle (id, make, model, price) values (47, 'GMC', 'Yukon', 78408);
insert into vehicle (id, make, model, price) values (48, 'Chevrolet', 'Express 1500', 34319);
insert into vehicle (id, make, model, price) values (49, 'Cadillac', 'SRX', 63019);
insert into vehicle (id, make, model, price) values (50, 'Audi', 'Allroad', 86751);
insert into vehicle (id, make, model, price) values (51, 'Mercedes-Benz', 'SL-Class', 70725);
insert into vehicle (id, make, model, price) values (52, 'Dodge', 'Caravan', 79933);
insert into vehicle (id, make, model, price) values (53, 'Acura', 'RL', 75273);
insert into vehicle (id, make, model, price) values (54, 'Mercury', 'Grand Marquis', 74200);
insert into vehicle (id, make, model, price) values (55, 'Chevrolet', 'Astro', 58302);
insert into vehicle (id, make, model, price) values (56, 'Volkswagen', 'Jetta', 89732);
insert into vehicle (id, make, model, price) values (57, 'Hyundai', 'Elantra', 62992);
insert into vehicle (id, make, model, price) values (58, 'Toyota', 'Camry Solara', 14386);
insert into vehicle (id, make, model, price) values (59, 'Suzuki', 'Sidekick', 21872);
insert into vehicle (id, make, model, price) values (60, 'Dodge', 'Stealth', 40816);
insert into vehicle (id, make, model, price) values (61, 'Isuzu', 'Oasis', 15360);
insert into vehicle (id, make, model, price) values (62, 'Honda', 'Civic', 19032);
insert into vehicle (id, make, model, price) values (63, 'Mercedes-Benz', 'S-Class', 81270);
insert into vehicle (id, make, model, price) values (64, 'Mazda', 'Familia', 42219);
insert into vehicle (id, make, model, price) values (65, 'Cadillac', 'Seville', 52043);
insert into vehicle (id, make, model, price) values (66, 'Bentley', 'Continental Super', 99541);
insert into vehicle (id, make, model, price) values (67, 'Mercedes-Benz', 'C-Class', 28833);
insert into vehicle (id, make, model, price) values (68, 'Ford', 'Expedition', 72869);
insert into vehicle (id, make, model, price) values (69, 'Suzuki', 'Vitara', 37259);
insert into vehicle (id, make, model, price) values (70, 'Lexus', 'LS', 18753);
insert into vehicle (id, make, model, price) values (71, 'Pontiac', 'LeMans', 79881);
insert into vehicle (id, make, model, price) values (72, 'Acura', 'Legend', 79590);
insert into vehicle (id, make, model, price) values (73, 'Chevrolet', 'Camaro', 16103);
insert into vehicle (id, make, model, price) values (74, 'Nissan', '300ZX', 28279);
insert into vehicle (id, make, model, price) values (75, 'Mercury', 'Mariner', 42925);
insert into vehicle (id, make, model, price) values (76, 'Acura', 'SLX', 67120);
insert into vehicle (id, make, model, price) values (77, 'Mitsubishi', 'Expo', 22359);
insert into vehicle (id, make, model, price) values (78, 'Subaru', 'Impreza', 69154);
insert into vehicle (id, make, model, price) values (79, 'Mercedes-Benz', 'SLR McLaren', 81696);
insert into vehicle (id, make, model, price) values (80, 'Lexus', 'LS', 11323);
insert into vehicle (id, make, model, price) values (81, 'Ferrari', '612 Scaglietti', 10576);
insert into vehicle (id, make, model, price) values (82, 'Mitsubishi', 'Pajero', 49845);
insert into vehicle (id, make, model, price) values (83, 'Ferrari', 'F430', 95558);
insert into vehicle (id, make, model, price) values (84, 'Nissan', 'Pathfinder', 79867);
insert into vehicle (id, make, model, price) values (85, 'Kia', 'Borrego', 79424);
insert into vehicle (id, make, model, price) values (86, 'Volkswagen', 'Jetta', 51968);
insert into vehicle (id, make, model, price) values (87, 'Toyota', 'Venza', 55026);
insert into vehicle (id, make, model, price) values (88, 'Dodge', 'Ram Van B150', 58710);
insert into vehicle (id, make, model, price) values (89, 'Toyota', 'Celica', 28978);
insert into vehicle (id, make, model, price) values (90, 'Pontiac', 'Vibe', 19347);
insert into vehicle (id, make, model, price) values (91, 'Isuzu', 'Hombre', 86596);
insert into vehicle (id, make, model, price) values (92, 'Ford', 'Courier', 46773);
insert into vehicle (id, make, model, price) values (93, 'Volvo', 'S80', 87507);
insert into vehicle (id, make, model, price) values (94, 'Lexus', 'SC', 77181);
insert into vehicle (id, make, model, price) values (95, 'Acura', 'TL', 15433);
insert into vehicle (id, make, model, price) values (96, 'Dodge', 'Dakota', 60421);
insert into vehicle (id, make, model, price) values (97, 'Volvo', 'C30', 58050);
insert into vehicle (id, make, model, price) values (98, 'Mitsubishi', 'Space', 77761);
insert into vehicle (id, make, model, price) values (99, 'Volvo', '940', 16228);
insert into vehicle (id, make, model, price) values (100, 'Audi', 'RS4', 19001);
insert into vehicle (id, make, model, price) values (101, 'Mercedes-Benz', 'M-Class', 85397);
insert into vehicle (id, make, model, price) values (102, 'Audi', 'TT', 34668);
insert into vehicle (id, make, model, price) values (103, 'Jeep', 'Cherokee', 46102);
insert into vehicle (id, make, model, price) values (104, 'Nissan', '240SX', 10240);
insert into vehicle (id, make, model, price) values (105, 'Saab', '900', 21307);
insert into vehicle (id, make, model, price) values (106, 'Mitsubishi', 'Mirage', 61966);
insert into vehicle (id, make, model, price) values (107, 'Hummer', 'H1', 89359);
insert into vehicle (id, make, model, price) values (108, 'Ford', 'Taurus X', 87697);
insert into vehicle (id, make, model, price) values (109, 'Ford', 'E250', 67107);
insert into vehicle (id, make, model, price) values (110, 'Ford', 'E-350 Super Duty', 38906);
insert into vehicle (id, make, model, price) values (111, 'Chevrolet', 'Venture', 31879);
insert into vehicle (id, make, model, price) values (112, 'Mercedes-Benz', '500SL', 52514);
insert into vehicle (id, make, model, price) values (113, 'Plymouth', 'Laser', 33102);
insert into vehicle (id, make, model, price) values (114, 'Chevrolet', 'Suburban 2500', 27485);
insert into vehicle (id, make, model, price) values (115, 'Nissan', 'Sentra', 63065);
insert into vehicle (id, make, model, price) values (116, 'Dodge', 'Dakota Club', 83188);
insert into vehicle (id, make, model, price) values (117, 'Toyota', 'Land Cruiser', 19837);
insert into vehicle (id, make, model, price) values (118, 'Plymouth', 'Breeze', 90797);
insert into vehicle (id, make, model, price) values (119, 'Volkswagen', 'Fox', 20837);
insert into vehicle (id, make, model, price) values (120, 'Volkswagen', 'Touareg', 60091);
insert into vehicle (id, make, model, price) values (121, 'Ford', 'Aerostar', 56987);
insert into vehicle (id, make, model, price) values (122, 'GMC', 'Terrain', 57651);
insert into vehicle (id, make, model, price) values (123, 'Porsche', '911', 43004);
insert into vehicle (id, make, model, price) values (124, 'Nissan', 'NX', 84846);
insert into vehicle (id, make, model, price) values (125, 'Porsche', '911', 81840);
insert into vehicle (id, make, model, price) values (126, 'Lexus', 'GS', 80908);
insert into vehicle (id, make, model, price) values (127, 'Hyundai', 'Tiburon', 25338);
insert into vehicle (id, make, model, price) values (128, 'Toyota', 'Avalon', 85376);
insert into vehicle (id, make, model, price) values (129, 'GMC', 'Vandura G2500', 31998);
insert into vehicle (id, make, model, price) values (130, 'Ford', 'F-Series', 51275);
insert into vehicle (id, make, model, price) values (131, 'Lincoln', 'MKX', 44603);
insert into vehicle (id, make, model, price) values (132, 'Buick', 'Somerset', 78733);
insert into vehicle (id, make, model, price) values (133, 'Rolls-Royce', 'Ghost', 66641);
insert into vehicle (id, make, model, price) values (134, 'Volvo', 'XC60', 13710);
insert into vehicle (id, make, model, price) values (135, 'Ford', 'Ranger', 32362);
insert into vehicle (id, make, model, price) values (136, 'Ford', 'Bronco', 11073);
insert into vehicle (id, make, model, price) values (137, 'Porsche', '968', 27224);
insert into vehicle (id, make, model, price) values (138, 'Honda', 'Odyssey', 85724);
insert into vehicle (id, make, model, price) values (139, 'Dodge', 'D250', 67127);
insert into vehicle (id, make, model, price) values (140, 'Mercedes-Benz', 'CLK-Class', 81773);
insert into vehicle (id, make, model, price) values (141, 'Buick', 'Electra', 81043);
insert into vehicle (id, make, model, price) values (142, 'Chevrolet', 'Suburban 2500', 37697);
insert into vehicle (id, make, model, price) values (143, 'Pontiac', 'Grand Prix', 25218);
insert into vehicle (id, make, model, price) values (144, 'Chevrolet', 'Corvette', 10745);
insert into vehicle (id, make, model, price) values (145, 'Corbin', 'Sparrow', 27013);
insert into vehicle (id, make, model, price) values (146, 'Mazda', 'Protege', 69684);
insert into vehicle (id, make, model, price) values (147, 'Kia', 'Borrego', 85460);
insert into vehicle (id, make, model, price) values (148, 'Toyota', 'Avalon', 48001);
insert into vehicle (id, make, model, price) values (149, 'Mazda', 'B-Series Plus', 44659);
insert into vehicle (id, make, model, price) values (150, 'Ford', 'Focus ST', 61789);
insert into vehicle (id, make, model, price) values (151, 'Buick', 'Century', 31947);
insert into vehicle (id, make, model, price) values (152, 'BMW', '7 Series', 87990);
insert into vehicle (id, make, model, price) values (153, 'Isuzu', 'Ascender', 51720);
insert into vehicle (id, make, model, price) values (154, 'Isuzu', 'Oasis', 11447);
insert into vehicle (id, make, model, price) values (155, 'Chrysler', 'Concorde', 17401);
insert into vehicle (id, make, model, price) values (156, 'Dodge', 'Durango', 55143);
insert into vehicle (id, make, model, price) values (157, 'GMC', 'Canyon', 98077);
insert into vehicle (id, make, model, price) values (158, 'Pontiac', 'Grand Prix', 46824);
insert into vehicle (id, make, model, price) values (159, 'Oldsmobile', 'Cutlass Supreme', 21262);
insert into vehicle (id, make, model, price) values (160, 'Land Rover', 'Discovery', 98149);
insert into vehicle (id, make, model, price) values (161, 'Mazda', 'B2600', 69289);
insert into vehicle (id, make, model, price) values (162, 'Jaguar', 'XJ Series', 19229);
insert into vehicle (id, make, model, price) values (163, 'Isuzu', 'Rodeo', 95621);
insert into vehicle (id, make, model, price) values (164, 'Mitsubishi', 'Mirage', 55770);
insert into vehicle (id, make, model, price) values (165, 'Cadillac', 'DeVille', 66956);
insert into vehicle (id, make, model, price) values (166, 'Mercury', 'Mariner', 14195);
insert into vehicle (id, make, model, price) values (167, 'Volvo', 'S60', 76929);
insert into vehicle (id, make, model, price) values (168, 'Toyota', 'Matrix', 20663);
insert into vehicle (id, make, model, price) values (169, 'Saab', '9-5', 29328);
insert into vehicle (id, make, model, price) values (170, 'Subaru', 'Legacy', 74077);
insert into vehicle (id, make, model, price) values (171, 'Mercury', 'Milan', 92906);
insert into vehicle (id, make, model, price) values (172, 'Jaguar', 'XJ Series', 51550);
insert into vehicle (id, make, model, price) values (173, 'Honda', 'Civic', 27240);
insert into vehicle (id, make, model, price) values (174, 'Buick', 'Park Avenue', 60395);
insert into vehicle (id, make, model, price) values (175, 'Jaguar', 'XF', 93457);
insert into vehicle (id, make, model, price) values (176, 'Ford', 'E250', 58324);
insert into vehicle (id, make, model, price) values (177, 'Ferrari', '612 Scaglietti', 46026);
insert into vehicle (id, make, model, price) values (178, 'Land Rover', 'LR2', 29340);
insert into vehicle (id, make, model, price) values (179, 'Lexus', 'SC', 21170);
insert into vehicle (id, make, model, price) values (180, 'Pontiac', 'Firebird Trans Am', 43484);
insert into vehicle (id, make, model, price) values (181, 'Mercedes-Benz', 'E-Class', 36236);
insert into vehicle (id, make, model, price) values (182, 'Maserati', '228', 38680);
insert into vehicle (id, make, model, price) values (183, 'Ford', 'F350', 82786);
insert into vehicle (id, make, model, price) values (184, 'Volkswagen', 'Cabriolet', 64063);
insert into vehicle (id, make, model, price) values (185, 'Ford', 'Mustang', 54912);
insert into vehicle (id, make, model, price) values (186, 'Ford', 'Mustang', 95278);
insert into vehicle (id, make, model, price) values (187, 'Acura', 'Legend', 99997);
insert into vehicle (id, make, model, price) values (188, 'Mercedes-Benz', 'Sprinter', 89563);
insert into vehicle (id, make, model, price) values (189, 'GMC', 'Rally Wagon 2500', 35208);
insert into vehicle (id, make, model, price) values (190, 'Chevrolet', 'Prizm', 76667);
insert into vehicle (id, make, model, price) values (191, 'BMW', 'X6', 60104);
insert into vehicle (id, make, model, price) values (192, 'GMC', 'Yukon', 58188);
insert into vehicle (id, make, model, price) values (193, 'GMC', 'Savana', 38416);
insert into vehicle (id, make, model, price) values (194, 'Pontiac', 'Firebird', 47699);
insert into vehicle (id, make, model, price) values (195, 'Ford', 'Crown Victoria', 48874);
insert into vehicle (id, make, model, price) values (196, 'Subaru', 'Legacy', 37522);
insert into vehicle (id, make, model, price) values (197, 'Mercedes-Benz', 'SL-Class', 54132);
insert into vehicle (id, make, model, price) values (198, 'Lamborghini', 'Countach', 70632);
insert into vehicle (id, make, model, price) values (199, 'Suzuki', 'XL-7', 85619);
insert into vehicle (id, make, model, price) values (200, 'Mercury', 'Sable', 44749);
insert into vehicle (id, make, model, price) values (201, 'Porsche', 'Cayenne', 96556);
insert into vehicle (id, make, model, price) values (202, 'Mercury', 'Grand Marquis', 33704);
insert into vehicle (id, make, model, price) values (203, 'Plymouth', 'Prowler', 55425);
insert into vehicle (id, make, model, price) values (204, 'Lincoln', 'Navigator', 92145);
insert into vehicle (id, make, model, price) values (205, 'Land Rover', 'LR3', 40505);
insert into vehicle (id, make, model, price) values (206, 'Chrysler', 'LeBaron', 91341);
insert into vehicle (id, make, model, price) values (207, 'Mazda', 'Mazdaspeed 3', 82778);
insert into vehicle (id, make, model, price) values (208, 'Lincoln', 'Navigator', 11641);
insert into vehicle (id, make, model, price) values (209, 'Audi', 'A8', 32312);
insert into vehicle (id, make, model, price) values (210, 'BMW', 'M5', 10272);
insert into vehicle (id, make, model, price) values (211, 'Nissan', 'Pathfinder', 13290);
insert into vehicle (id, make, model, price) values (212, 'Ford', 'Aspire', 19067);
insert into vehicle (id, make, model, price) values (213, 'BMW', '7 Series', 59846);
insert into vehicle (id, make, model, price) values (214, 'Mitsubishi', 'Montero Sport', 60956);
insert into vehicle (id, make, model, price) values (215, 'Mitsubishi', 'Eclipse', 42929);
insert into vehicle (id, make, model, price) values (216, 'Ford', 'F350', 51688);
insert into vehicle (id, make, model, price) values (217, 'Dodge', 'Challenger', 42283);
insert into vehicle (id, make, model, price) values (218, 'Mercury', 'Montego', 89401);
insert into vehicle (id, make, model, price) values (219, 'Ford', 'Mustang', 65004);
insert into vehicle (id, make, model, price) values (220, 'Land Rover', 'Defender 90', 94284);
insert into vehicle (id, make, model, price) values (221, 'Pontiac', 'Firefly', 60714);
insert into vehicle (id, make, model, price) values (222, 'Hummer', 'H2', 80808);
insert into vehicle (id, make, model, price) values (223, 'Jaguar', 'S-Type', 90547);
insert into vehicle (id, make, model, price) values (224, 'Mazda', 'RX-7', 73614);
insert into vehicle (id, make, model, price) values (225, 'BMW', '3 Series', 15973);
insert into vehicle (id, make, model, price) values (226, 'Hyundai', 'Sonata', 15492);
insert into vehicle (id, make, model, price) values (227, 'Chevrolet', 'APV', 35661);
insert into vehicle (id, make, model, price) values (228, 'Chevrolet', 'Cobalt', 26748);
insert into vehicle (id, make, model, price) values (229, 'Mitsubishi', 'Mighty Max', 19148);
insert into vehicle (id, make, model, price) values (230, 'Suzuki', 'Sidekick', 99452);
insert into vehicle (id, make, model, price) values (231, 'Dodge', 'Caravan', 38569);
insert into vehicle (id, make, model, price) values (232, 'Ford', 'Tempo', 13152);
insert into vehicle (id, make, model, price) values (233, 'Ford', 'Thunderbird', 25566);
insert into vehicle (id, make, model, price) values (234, 'Toyota', 'Camry Solara', 54321);
insert into vehicle (id, make, model, price) values (235, 'Toyota', 'Sienna', 22221);
insert into vehicle (id, make, model, price) values (236, 'Plymouth', 'Breeze', 97275);
insert into vehicle (id, make, model, price) values (237, 'Chrysler', 'Sebring', 91702);
insert into vehicle (id, make, model, price) values (238, 'Ford', 'Contour', 66459);
insert into vehicle (id, make, model, price) values (239, 'Audi', 'Q7', 66774);
insert into vehicle (id, make, model, price) values (240, 'Mercedes-Benz', 'CLK-Class', 83194);
insert into vehicle (id, make, model, price) values (241, 'GMC', 'Savana 1500', 44362);
insert into vehicle (id, make, model, price) values (242, 'Saturn', 'VUE', 10885);
insert into vehicle (id, make, model, price) values (243, 'Audi', 'A6', 85997);
insert into vehicle (id, make, model, price) values (244, 'Saturn', 'Aura', 78277);
insert into vehicle (id, make, model, price) values (245, 'Ford', 'LTD Crown Victoria', 65636);
insert into vehicle (id, make, model, price) values (246, 'Audi', 'A5', 87031);
insert into vehicle (id, make, model, price) values (247, 'Mercedes-Benz', 'W201', 16621);
insert into vehicle (id, make, model, price) values (248, 'Dodge', 'D250', 35977);
insert into vehicle (id, make, model, price) values (249, 'Oldsmobile', 'Cutlass Cruiser', 14813);
insert into vehicle (id, make, model, price) values (250, 'Mazda', 'Tribute', 43599);
insert into vehicle (id, make, model, price) values (251, 'Dodge', 'Ram 2500', 78778);
insert into vehicle (id, make, model, price) values (252, 'Mitsubishi', 'Expo', 41235);
insert into vehicle (id, make, model, price) values (253, 'Mercedes-Benz', '300SE', 87640);
insert into vehicle (id, make, model, price) values (254, 'Chevrolet', 'Avalanche', 39377);
insert into vehicle (id, make, model, price) values (255, 'Volkswagen', 'Cabriolet', 39079);
insert into vehicle (id, make, model, price) values (256, 'Chevrolet', 'Lumina', 94524);
insert into vehicle (id, make, model, price) values (257, 'Mazda', '626', 14681);
insert into vehicle (id, make, model, price) values (258, 'Mazda', 'B-Series Plus', 48628);
insert into vehicle (id, make, model, price) values (259, 'Chrysler', 'PT Cruiser', 74479);
insert into vehicle (id, make, model, price) values (260, 'Acura', 'RL', 46413);
insert into vehicle (id, make, model, price) values (261, 'Lincoln', 'MKZ', 59242);
insert into vehicle (id, make, model, price) values (262, 'Toyota', 'Camry Hybrid', 49468);
insert into vehicle (id, make, model, price) values (263, 'GMC', 'Yukon XL 1500', 30429);
insert into vehicle (id, make, model, price) values (264, 'Lincoln', 'Continental', 15166);
insert into vehicle (id, make, model, price) values (265, 'Mazda', '626', 60222);
insert into vehicle (id, make, model, price) values (266, 'Nissan', 'Sentra', 11654);
insert into vehicle (id, make, model, price) values (267, 'Dodge', 'Viper', 75720);
insert into vehicle (id, make, model, price) values (268, 'Kia', 'Sedona', 19381);
insert into vehicle (id, make, model, price) values (269, 'Acura', 'Vigor', 56813);
insert into vehicle (id, make, model, price) values (270, 'Mitsubishi', 'Eclipse', 12332);
insert into vehicle (id, make, model, price) values (271, 'Subaru', 'Legacy', 27433);
insert into vehicle (id, make, model, price) values (272, 'Ford', 'F350', 36207);
insert into vehicle (id, make, model, price) values (273, 'Ford', 'Transit Connect', 41207);
insert into vehicle (id, make, model, price) values (274, 'Chevrolet', 'Suburban 2500', 57578);
insert into vehicle (id, make, model, price) values (275, 'Ford', 'Bronco', 98107);
insert into vehicle (id, make, model, price) values (276, 'Oldsmobile', 'Cutlass', 55932);
insert into vehicle (id, make, model, price) values (277, 'Mercedes-Benz', 'CLK-Class', 77626);
insert into vehicle (id, make, model, price) values (278, 'Chevrolet', 'Aveo', 90121);
insert into vehicle (id, make, model, price) values (279, 'Cadillac', 'DTS', 24863);
insert into vehicle (id, make, model, price) values (280, 'GMC', '3500 Club Coupe', 75556);
insert into vehicle (id, make, model, price) values (281, 'Toyota', 'Tacoma', 90345);
insert into vehicle (id, make, model, price) values (282, 'Scion', 'xB', 42732);
insert into vehicle (id, make, model, price) values (283, 'Land Rover', 'LR2', 64888);
insert into vehicle (id, make, model, price) values (284, 'Volvo', 'S80', 32371);
insert into vehicle (id, make, model, price) values (285, 'Chevrolet', 'Beretta', 25317);
insert into vehicle (id, make, model, price) values (286, 'Toyota', 'Land Cruiser', 63586);
insert into vehicle (id, make, model, price) values (287, 'Mazda', 'Familia', 57506);
insert into vehicle (id, make, model, price) values (288, 'Mercury', 'Villager', 16680);
insert into vehicle (id, make, model, price) values (289, 'Maybach', '62', 85014);
insert into vehicle (id, make, model, price) values (290, 'Mercedes-Benz', 'SLS AMG', 76764);
insert into vehicle (id, make, model, price) values (291, 'Toyota', '4Runner', 29629);
insert into vehicle (id, make, model, price) values (292, 'Lexus', 'SC', 96693);
insert into vehicle (id, make, model, price) values (293, 'Saab', '9-5', 41219);
insert into vehicle (id, make, model, price) values (294, 'Audi', 'Quattro', 93588);
insert into vehicle (id, make, model, price) values (295, 'Volkswagen', 'Corrado', 57517);
insert into vehicle (id, make, model, price) values (296, 'Buick', 'Century', 62875);
insert into vehicle (id, make, model, price) values (297, 'Isuzu', 'Rodeo', 95234);
insert into vehicle (id, make, model, price) values (298, 'Suzuki', 'SJ', 79680);
insert into vehicle (id, make, model, price) values (299, 'Infiniti', 'QX', 18520);
insert into vehicle (id, make, model, price) values (300, 'Toyota', 'Sequoia', 63965);
insert into vehicle (id, make, model, price) values (301, 'Hyundai', 'Veracruz', 95654);
insert into vehicle (id, make, model, price) values (302, 'Mercedes-Benz', 'S-Class', 47470);
insert into vehicle (id, make, model, price) values (303, 'Suzuki', 'Equator', 93129);
insert into vehicle (id, make, model, price) values (304, 'Volvo', 'C70', 61857);
insert into vehicle (id, make, model, price) values (305, 'Lexus', 'RX', 58008);
insert into vehicle (id, make, model, price) values (306, 'Toyota', 'Tacoma Xtra', 38827);
insert into vehicle (id, make, model, price) values (307, 'Mercedes-Benz', 'E-Class', 52451);
insert into vehicle (id, make, model, price) values (308, 'Chevrolet', 'Silverado 2500', 81887);
insert into vehicle (id, make, model, price) values (309, 'Mazda', 'B2600', 30256);
insert into vehicle (id, make, model, price) values (310, 'Pontiac', '6000', 87414);
insert into vehicle (id, make, model, price) values (311, 'Mazda', 'CX-7', 80599);
insert into vehicle (id, make, model, price) values (312, 'Plymouth', 'Voyager', 42780);
insert into vehicle (id, make, model, price) values (313, 'Pontiac', 'Sunfire', 99377);
insert into vehicle (id, make, model, price) values (314, 'Ford', 'Taurus', 69167);
insert into vehicle (id, make, model, price) values (315, 'Volvo', 'S80', 50357);
insert into vehicle (id, make, model, price) values (316, 'Chevrolet', 'Camaro', 70149);
insert into vehicle (id, make, model, price) values (317, 'Infiniti', 'J', 43068);
insert into vehicle (id, make, model, price) values (318, 'Volvo', 'C30', 21628);
insert into vehicle (id, make, model, price) values (319, 'Dodge', 'Grand Caravan', 70487);
insert into vehicle (id, make, model, price) values (320, 'GMC', 'Envoy', 17199);
insert into vehicle (id, make, model, price) values (321, 'Chevrolet', 'Tahoe', 50402);
insert into vehicle (id, make, model, price) values (322, 'Chevrolet', 'G-Series 3500', 78405);
insert into vehicle (id, make, model, price) values (323, 'Dodge', 'Ram 1500', 45742);
insert into vehicle (id, make, model, price) values (324, 'Nissan', 'Altima', 51184);
insert into vehicle (id, make, model, price) values (325, 'Chevrolet', 'Avalanche', 56133);
insert into vehicle (id, make, model, price) values (326, 'Ford', 'Bronco', 38734);
insert into vehicle (id, make, model, price) values (327, 'Volkswagen', 'New Beetle', 30473);
insert into vehicle (id, make, model, price) values (328, 'Oldsmobile', 'Alero', 32744);
insert into vehicle (id, make, model, price) values (329, 'Kia', 'Sorento', 49931);
insert into vehicle (id, make, model, price) values (330, 'Lexus', 'IS-F', 28394);
insert into vehicle (id, make, model, price) values (331, 'Toyota', 'Xtra', 11062);
insert into vehicle (id, make, model, price) values (332, 'Pontiac', 'Tempest', 91593);
insert into vehicle (id, make, model, price) values (333, 'Chrysler', 'LeBaron', 96780);
insert into vehicle (id, make, model, price) values (334, 'Chrysler', 'LHS', 56160);
insert into vehicle (id, make, model, price) values (335, 'Oldsmobile', 'Achieva', 10120);
insert into vehicle (id, make, model, price) values (336, 'Volvo', 'S60', 71405);
insert into vehicle (id, make, model, price) values (337, 'Chevrolet', 'Corvette', 25837);
insert into vehicle (id, make, model, price) values (338, 'Jeep', 'Commander', 17662);
insert into vehicle (id, make, model, price) values (339, 'Toyota', 'Corolla', 45796);
insert into vehicle (id, make, model, price) values (340, 'Chevrolet', 'Camaro', 83400);
insert into vehicle (id, make, model, price) values (341, 'Acura', 'Integra', 34903);
insert into vehicle (id, make, model, price) values (342, 'Maybach', '62', 84926);
insert into vehicle (id, make, model, price) values (343, 'Audi', 'S6', 61145);
insert into vehicle (id, make, model, price) values (344, 'Ford', 'Thunderbird', 68716);
insert into vehicle (id, make, model, price) values (345, 'Dodge', 'Ram 50', 50835);
insert into vehicle (id, make, model, price) values (346, 'Chevrolet', 'Corvette', 51583);
insert into vehicle (id, make, model, price) values (347, 'Nissan', 'JUKE', 29336);
insert into vehicle (id, make, model, price) values (348, 'Hyundai', 'Scoupe', 88668);
insert into vehicle (id, make, model, price) values (349, 'Ford', 'Escort', 58104);
insert into vehicle (id, make, model, price) values (350, 'Toyota', 'Matrix', 99201);
insert into vehicle (id, make, model, price) values (351, 'Land Rover', 'Range Rover', 22954);
insert into vehicle (id, make, model, price) values (352, 'Cadillac', 'DeVille', 61799);
insert into vehicle (id, make, model, price) values (353, 'Dodge', 'Viper', 85504);
insert into vehicle (id, make, model, price) values (354, 'Mercedes-Benz', 'G-Class', 93702);
insert into vehicle (id, make, model, price) values (355, 'Jaguar', 'XK Series', 94095);
insert into vehicle (id, make, model, price) values (356, 'Ford', 'Mustang', 14053);
insert into vehicle (id, make, model, price) values (357, 'GMC', 'Savana 1500', 81387);
insert into vehicle (id, make, model, price) values (358, 'Volvo', '960', 86517);
insert into vehicle (id, make, model, price) values (359, 'Ford', 'Thunderbird', 17887);
insert into vehicle (id, make, model, price) values (360, 'Chrysler', 'Crossfire', 36031);
insert into vehicle (id, make, model, price) values (361, 'Chevrolet', 'Corvette', 94078);
insert into vehicle (id, make, model, price) values (362, 'Infiniti', 'G', 71557);
insert into vehicle (id, make, model, price) values (363, 'Ford', 'Fusion', 35809);
insert into vehicle (id, make, model, price) values (364, 'Honda', 'Insight', 22292);
insert into vehicle (id, make, model, price) values (365, 'Honda', 'CR-V', 36174);
insert into vehicle (id, make, model, price) values (366, 'Infiniti', 'Q', 10641);
insert into vehicle (id, make, model, price) values (367, 'Mercedes-Benz', 'S-Class', 35890);
insert into vehicle (id, make, model, price) values (368, 'Infiniti', 'G', 30777);
insert into vehicle (id, make, model, price) values (369, 'Toyota', '4Runner', 82601);
insert into vehicle (id, make, model, price) values (370, 'Mercury', 'Grand Marquis', 40875);
insert into vehicle (id, make, model, price) values (371, 'GMC', 'Envoy', 24031);
insert into vehicle (id, make, model, price) values (372, 'Acura', 'RL', 80710);
insert into vehicle (id, make, model, price) values (373, 'Jeep', 'Grand Cherokee', 47440);
insert into vehicle (id, make, model, price) values (374, 'Dodge', 'Ram 3500 Club', 69313);
insert into vehicle (id, make, model, price) values (375, 'Aston Martin', 'Rapide', 50363);
insert into vehicle (id, make, model, price) values (376, 'Saab', '9-5', 50740);
insert into vehicle (id, make, model, price) values (377, 'Chevrolet', 'Camaro', 87097);
insert into vehicle (id, make, model, price) values (378, 'Maserati', 'GranTurismo', 90256);
insert into vehicle (id, make, model, price) values (379, 'Porsche', '911', 22267);
insert into vehicle (id, make, model, price) values (380, 'Lexus', 'SC', 90303);
insert into vehicle (id, make, model, price) values (381, 'Chevrolet', 'Silverado 3500', 21888);
insert into vehicle (id, make, model, price) values (382, 'Saturn', 'Outlook', 62652);
insert into vehicle (id, make, model, price) values (383, 'Chrysler', 'PT Cruiser', 49281);
insert into vehicle (id, make, model, price) values (384, 'Isuzu', 'Trooper', 84122);
insert into vehicle (id, make, model, price) values (385, 'Mazda', 'GLC', 94427);
insert into vehicle (id, make, model, price) values (386, 'Ford', 'E350', 28629);
insert into vehicle (id, make, model, price) values (387, 'Chevrolet', 'Silverado 2500', 95105);
insert into vehicle (id, make, model, price) values (388, 'Ford', 'Flex', 48193);
insert into vehicle (id, make, model, price) values (389, 'GMC', 'Yukon', 21740);
insert into vehicle (id, make, model, price) values (390, 'BMW', '7 Series', 70009);
insert into vehicle (id, make, model, price) values (391, 'GMC', 'Sonoma', 70866);
insert into vehicle (id, make, model, price) values (392, 'BMW', 'X5', 36229);
insert into vehicle (id, make, model, price) values (393, 'Mercury', 'Sable', 73951);
insert into vehicle (id, make, model, price) values (394, 'Lexus', 'LX', 52236);
insert into vehicle (id, make, model, price) values (395, 'Toyota', 'Camry', 56955);
insert into vehicle (id, make, model, price) values (396, 'Cadillac', 'DeVille', 23365);
insert into vehicle (id, make, model, price) values (397, 'Dodge', 'Ram 2500 Club', 20996);
insert into vehicle (id, make, model, price) values (398, 'Dodge', 'Caliber', 86002);
insert into vehicle (id, make, model, price) values (399, 'Daewoo', 'Lanos', 47341);
insert into vehicle (id, make, model, price) values (400, 'Plymouth', 'Voyager', 48486);
insert into vehicle (id, make, model, price) values (401, 'Toyota', 'Land Cruiser', 46245);
insert into vehicle (id, make, model, price) values (402, 'Dodge', 'Caravan', 15232);
insert into vehicle (id, make, model, price) values (403, 'Chevrolet', 'Metro', 45455);
insert into vehicle (id, make, model, price) values (404, 'Mitsubishi', 'Raider', 72574);
insert into vehicle (id, make, model, price) values (405, 'Nissan', 'Sentra', 36180);
insert into vehicle (id, make, model, price) values (406, 'Lincoln', 'MKS', 71929);
insert into vehicle (id, make, model, price) values (407, 'Fiat', 'Nuova 500', 91462);
insert into vehicle (id, make, model, price) values (408, 'Toyota', 'MR2', 92556);
insert into vehicle (id, make, model, price) values (409, 'Land Rover', 'Range Rover', 81415);
insert into vehicle (id, make, model, price) values (410, 'Suzuki', 'Aerio', 25353);
insert into vehicle (id, make, model, price) values (411, 'Volkswagen', 'New Beetle', 42609);
insert into vehicle (id, make, model, price) values (412, 'Lexus', 'RX', 38419);
insert into vehicle (id, make, model, price) values (413, 'Toyota', 'Corolla', 76555);
insert into vehicle (id, make, model, price) values (414, 'Jaguar', 'XK', 94461);
insert into vehicle (id, make, model, price) values (415, 'Land Rover', 'Discovery', 24401);
insert into vehicle (id, make, model, price) values (416, 'Chevrolet', 'Camaro', 21641);
insert into vehicle (id, make, model, price) values (417, 'Chevrolet', 'Corvette', 80954);
insert into vehicle (id, make, model, price) values (418, 'BMW', '8 Series', 60990);
insert into vehicle (id, make, model, price) values (419, 'Ford', 'Mustang', 99673);
insert into vehicle (id, make, model, price) values (420, 'Mercedes-Benz', 'SLS-Class', 44204);
insert into vehicle (id, make, model, price) values (421, 'Ford', 'F-Series', 46812);
insert into vehicle (id, make, model, price) values (422, 'Volvo', 'C70', 26116);
insert into vehicle (id, make, model, price) values (423, 'Scion', 'tC', 28687);
insert into vehicle (id, make, model, price) values (424, 'Acura', 'Integra', 98886);
insert into vehicle (id, make, model, price) values (425, 'Chevrolet', 'Silverado 3500', 71159);
insert into vehicle (id, make, model, price) values (426, 'Jeep', 'Compass', 66481);
insert into vehicle (id, make, model, price) values (427, 'Mazda', 'B-Series', 61625);
insert into vehicle (id, make, model, price) values (428, 'Porsche', '911', 76911);
insert into vehicle (id, make, model, price) values (429, 'Chevrolet', 'Sportvan G30', 88246);
insert into vehicle (id, make, model, price) values (430, 'Mercury', 'Topaz', 63955);
insert into vehicle (id, make, model, price) values (431, 'Subaru', 'Legacy', 69773);
insert into vehicle (id, make, model, price) values (432, 'Buick', 'Century', 97001);
insert into vehicle (id, make, model, price) values (433, 'Mitsubishi', 'Pajero', 12867);
insert into vehicle (id, make, model, price) values (434, 'Cadillac', 'DTS', 25646);
insert into vehicle (id, make, model, price) values (435, 'Honda', 'Odyssey', 33161);
insert into vehicle (id, make, model, price) values (436, 'Mercedes-Benz', 'E-Class', 99377);
insert into vehicle (id, make, model, price) values (437, 'Saab', '900', 89541);
insert into vehicle (id, make, model, price) values (438, 'Lincoln', 'Town Car', 92640);
insert into vehicle (id, make, model, price) values (439, 'Dodge', 'Caliber', 59752);
insert into vehicle (id, make, model, price) values (440, 'Mercedes-Benz', 'CLS-Class', 83348);
insert into vehicle (id, make, model, price) values (441, 'Chevrolet', 'Silverado 1500', 82740);
insert into vehicle (id, make, model, price) values (442, 'Ford', 'Fiesta', 25092);
insert into vehicle (id, make, model, price) values (443, 'Infiniti', 'QX56', 47502);
insert into vehicle (id, make, model, price) values (444, 'Ford', 'Econoline E150', 77671);
insert into vehicle (id, make, model, price) values (445, 'Mitsubishi', 'Montero Sport', 42653);
insert into vehicle (id, make, model, price) values (446, 'Volvo', 'V40', 60210);
insert into vehicle (id, make, model, price) values (447, 'Ford', 'Explorer Sport', 98128);
insert into vehicle (id, make, model, price) values (448, 'Lexus', 'LX', 83546);
insert into vehicle (id, make, model, price) values (449, 'Chevrolet', 'Tracker', 38858);
insert into vehicle (id, make, model, price) values (450, 'Ford', 'Windstar', 13974);
insert into vehicle (id, make, model, price) values (451, 'Ford', 'E-Series', 13627);
insert into vehicle (id, make, model, price) values (452, 'Acura', 'NSX', 52147);
insert into vehicle (id, make, model, price) values (453, 'Kia', 'Forte', 32329);
insert into vehicle (id, make, model, price) values (454, 'Dodge', 'Ram 2500 Club', 47618);
insert into vehicle (id, make, model, price) values (455, 'Volkswagen', 'Passat', 26723);
insert into vehicle (id, make, model, price) values (456, 'Ford', 'Mustang', 72886);
insert into vehicle (id, make, model, price) values (457, 'Mercury', 'Sable', 91120);
insert into vehicle (id, make, model, price) values (458, 'Ford', 'Fiesta', 59109);
insert into vehicle (id, make, model, price) values (459, 'GMC', 'Yukon XL 2500', 55882);
insert into vehicle (id, make, model, price) values (460, 'Nissan', '240SX', 19960);
insert into vehicle (id, make, model, price) values (461, 'Ford', 'E-Series', 10480);
insert into vehicle (id, make, model, price) values (462, 'Lexus', 'IS', 18406);
insert into vehicle (id, make, model, price) values (463, 'Acura', 'TL', 30033);
insert into vehicle (id, make, model, price) values (464, 'Lexus', 'LX', 69570);
insert into vehicle (id, make, model, price) values (465, 'Suzuki', 'Swift', 73453);
insert into vehicle (id, make, model, price) values (466, 'GMC', 'Safari', 27475);
insert into vehicle (id, make, model, price) values (467, 'Lincoln', 'Town Car', 42578);
insert into vehicle (id, make, model, price) values (468, 'Dodge', 'Ram 2500', 26858);
insert into vehicle (id, make, model, price) values (469, 'Ford', 'LTD Crown Victoria', 67748);
insert into vehicle (id, make, model, price) values (470, 'Pontiac', 'Firefly', 81690);
insert into vehicle (id, make, model, price) values (471, 'BMW', 'X3', 94078);
insert into vehicle (id, make, model, price) values (472, 'Mitsubishi', 'L300', 51648);
insert into vehicle (id, make, model, price) values (473, 'Toyota', 'MR2', 41032);
insert into vehicle (id, make, model, price) values (474, 'Chevrolet', 'Silverado 2500', 64053);
insert into vehicle (id, make, model, price) values (475, 'Infiniti', 'G25', 63867);
insert into vehicle (id, make, model, price) values (476, 'Subaru', 'Baja', 58085);
insert into vehicle (id, make, model, price) values (477, 'Ford', 'Festiva', 87201);
insert into vehicle (id, make, model, price) values (478, 'Mitsubishi', 'Pajero', 58842);
insert into vehicle (id, make, model, price) values (479, 'Oldsmobile', 'Silhouette', 38864);
insert into vehicle (id, make, model, price) values (480, 'Buick', 'Regal', 74149);
insert into vehicle (id, make, model, price) values (481, 'GMC', 'Yukon', 73177);
insert into vehicle (id, make, model, price) values (482, 'GMC', 'Suburban 2500', 21906);
insert into vehicle (id, make, model, price) values (483, 'Chevrolet', 'Express 2500', 22010);
insert into vehicle (id, make, model, price) values (484, 'Toyota', '4Runner', 19166);
insert into vehicle (id, make, model, price) values (485, 'Audi', 'TT', 39669);
insert into vehicle (id, make, model, price) values (486, 'Lexus', 'GS', 49911);
insert into vehicle (id, make, model, price) values (487, 'Dodge', 'Ram 2500', 94045);
insert into vehicle (id, make, model, price) values (488, 'Mazda', 'CX-7', 33536);
insert into vehicle (id, make, model, price) values (489, 'Mazda', 'Miata MX-5', 29603);
insert into vehicle (id, make, model, price) values (490, 'Infiniti', 'Q', 27319);
insert into vehicle (id, make, model, price) values (491, 'Volkswagen', 'GTI', 72312);
insert into vehicle (id, make, model, price) values (492, 'GMC', 'Sonoma Club Coupe', 24155);
insert into vehicle (id, make, model, price) values (493, 'Volvo', 'S60', 89959);
insert into vehicle (id, make, model, price) values (494, 'Pontiac', 'Firebird', 66232);
insert into vehicle (id, make, model, price) values (495, 'Mazda', 'Protege', 89335);
insert into vehicle (id, make, model, price) values (496, 'Ford', 'Crown Victoria', 83887);
insert into vehicle (id, make, model, price) values (497, 'Ford', 'Econoline E250', 15978);
insert into vehicle (id, make, model, price) values (498, 'Chevrolet', 'Camaro', 21846);
insert into vehicle (id, make, model, price) values (499, 'Isuzu', 'Axiom', 61511);
insert into vehicle (id, make, model, price) values (500, 'BMW', 'M3', 78536);
insert into vehicle (id, make, model, price) values (501, 'Volkswagen', 'Cabriolet', 10190);
insert into vehicle (id, make, model, price) values (502, 'Mercury', 'Grand Marquis', 87109);
insert into vehicle (id, make, model, price) values (503, 'Volvo', 'XC70', 43210);
insert into vehicle (id, make, model, price) values (504, 'GMC', '2500', 29094);
insert into vehicle (id, make, model, price) values (505, 'Infiniti', 'G37', 81781);
insert into vehicle (id, make, model, price) values (506, 'Chevrolet', 'Suburban 2500', 10615);
insert into vehicle (id, make, model, price) values (507, 'GMC', 'Yukon Denali', 39999);
insert into vehicle (id, make, model, price) values (508, 'Pontiac', 'Bonneville', 95838);
insert into vehicle (id, make, model, price) values (509, 'Chevrolet', 'Malibu', 68713);
insert into vehicle (id, make, model, price) values (510, 'Mercedes-Benz', '300SL', 94649);
insert into vehicle (id, make, model, price) values (511, 'Oldsmobile', 'Silhouette', 32047);
insert into vehicle (id, make, model, price) values (512, 'Audi', 'RS4', 96462);
insert into vehicle (id, make, model, price) values (513, 'Jaguar', 'XK', 70657);
insert into vehicle (id, make, model, price) values (514, 'Nissan', 'Xterra', 45457);
insert into vehicle (id, make, model, price) values (515, 'Daewoo', 'Nubira', 11515);
insert into vehicle (id, make, model, price) values (516, 'Suzuki', 'Forenza', 54483);
insert into vehicle (id, make, model, price) values (517, 'GMC', '3500', 26748);
insert into vehicle (id, make, model, price) values (518, 'Mazda', 'Millenia', 75890);
insert into vehicle (id, make, model, price) values (519, 'Chevrolet', 'Tahoe', 26908);
insert into vehicle (id, make, model, price) values (520, 'Mazda', 'Mazda5', 76868);
insert into vehicle (id, make, model, price) values (521, 'Honda', 'Ridgeline', 80590);
insert into vehicle (id, make, model, price) values (522, 'Oldsmobile', 'Cutlass Supreme', 45423);
insert into vehicle (id, make, model, price) values (523, 'Ford', 'E350', 45797);
insert into vehicle (id, make, model, price) values (524, 'Hyundai', 'Elantra', 30252);
insert into vehicle (id, make, model, price) values (525, 'Jeep', 'Patriot', 20048);
insert into vehicle (id, make, model, price) values (526, 'Audi', 'S4', 80137);
insert into vehicle (id, make, model, price) values (527, 'Ford', 'Crown Victoria', 94516);
insert into vehicle (id, make, model, price) values (528, 'Buick', 'Hearse', 93535);
insert into vehicle (id, make, model, price) values (529, 'Dodge', 'Ram Van 1500', 58935);
insert into vehicle (id, make, model, price) values (530, 'Toyota', '4Runner', 57301);
insert into vehicle (id, make, model, price) values (531, 'Chevrolet', 'S10 Blazer', 86140);
insert into vehicle (id, make, model, price) values (532, 'Mercedes-Benz', 'CLK-Class', 52759);
insert into vehicle (id, make, model, price) values (533, 'Acura', 'NSX', 73804);
insert into vehicle (id, make, model, price) values (534, 'Lamborghini', 'Countach', 98418);
insert into vehicle (id, make, model, price) values (535, 'Mercury', 'Villager', 84352);
insert into vehicle (id, make, model, price) values (536, 'Mercedes-Benz', 'SL-Class', 81096);
insert into vehicle (id, make, model, price) values (537, 'Chevrolet', 'Malibu', 79336);
insert into vehicle (id, make, model, price) values (538, 'Ford', 'Crown Victoria', 48517);
insert into vehicle (id, make, model, price) values (539, 'Nissan', '200SX', 58935);
insert into vehicle (id, make, model, price) values (540, 'Buick', 'LeSabre', 57211);
insert into vehicle (id, make, model, price) values (541, 'Isuzu', 'Hombre Space', 91448);
insert into vehicle (id, make, model, price) values (542, 'Lexus', 'IS', 51716);
insert into vehicle (id, make, model, price) values (543, 'Mitsubishi', 'Montero', 89615);
insert into vehicle (id, make, model, price) values (544, 'Buick', 'Riviera', 56735);
insert into vehicle (id, make, model, price) values (545, 'Pontiac', 'Gemini', 78741);
insert into vehicle (id, make, model, price) values (546, 'Ford', 'Bronco', 51379);
insert into vehicle (id, make, model, price) values (547, 'Dodge', 'Ram Van B350', 44169);
insert into vehicle (id, make, model, price) values (548, 'Buick', 'Electra', 27379);
insert into vehicle (id, make, model, price) values (549, 'Mercedes-Benz', 'SLR McLaren', 94859);
insert into vehicle (id, make, model, price) values (550, 'Dodge', 'Charger', 20823);
insert into vehicle (id, make, model, price) values (551, 'Pontiac', 'G5', 18131);
insert into vehicle (id, make, model, price) values (552, 'Suzuki', 'SJ', 61643);
insert into vehicle (id, make, model, price) values (553, 'Volvo', 'C30', 37668);
insert into vehicle (id, make, model, price) values (554, 'Lincoln', 'Continental', 12464);
insert into vehicle (id, make, model, price) values (555, 'Ferrari', '599 GTB Fiorano', 92734);
insert into vehicle (id, make, model, price) values (556, 'Ford', 'F350', 55395);
insert into vehicle (id, make, model, price) values (557, 'Mercedes-Benz', 'GL-Class', 54066);
insert into vehicle (id, make, model, price) values (558, 'Mercury', 'Villager', 48668);
insert into vehicle (id, make, model, price) values (559, 'Volvo', 'XC60', 55418);
insert into vehicle (id, make, model, price) values (560, 'Ford', 'Taurus', 97918);
insert into vehicle (id, make, model, price) values (561, 'Cadillac', 'XLR-V', 75373);
insert into vehicle (id, make, model, price) values (562, 'Dodge', 'Ram 3500', 34264);
insert into vehicle (id, make, model, price) values (563, 'Chrysler', 'Pacifica', 86201);
insert into vehicle (id, make, model, price) values (564, 'Dodge', 'Dakota', 92942);
insert into vehicle (id, make, model, price) values (565, 'Jeep', 'Commander', 87165);
insert into vehicle (id, make, model, price) values (566, 'Audi', 'Allroad', 11403);
insert into vehicle (id, make, model, price) values (567, 'Mercedes-Benz', 'CLS-Class', 75129);
insert into vehicle (id, make, model, price) values (568, 'Lexus', 'LS', 36864);
insert into vehicle (id, make, model, price) values (569, 'Mitsubishi', 'Eclipse', 10409);
insert into vehicle (id, make, model, price) values (570, 'Mazda', 'RX-8', 77288);
insert into vehicle (id, make, model, price) values (571, 'Dodge', 'Neon', 74605);
insert into vehicle (id, make, model, price) values (572, 'Honda', 'del Sol', 57271);
insert into vehicle (id, make, model, price) values (573, 'Nissan', 'Frontier', 94115);
insert into vehicle (id, make, model, price) values (574, 'Ford', 'Thunderbird', 64481);
insert into vehicle (id, make, model, price) values (575, 'Suzuki', 'Kizashi', 12379);
insert into vehicle (id, make, model, price) values (576, 'Ford', 'Escape', 57400);
insert into vehicle (id, make, model, price) values (577, 'Plymouth', 'Laser', 51780);
insert into vehicle (id, make, model, price) values (578, 'Lamborghini', 'Countach', 35238);
insert into vehicle (id, make, model, price) values (579, 'Chevrolet', 'Camaro', 68097);
insert into vehicle (id, make, model, price) values (580, 'Mercury', 'Topaz', 58095);
insert into vehicle (id, make, model, price) values (581, 'Toyota', '4Runner', 76247);
insert into vehicle (id, make, model, price) values (582, 'Jaguar', 'XJ Series', 39810);
insert into vehicle (id, make, model, price) values (583, 'Mercedes-Benz', 'E-Class', 39915);
insert into vehicle (id, make, model, price) values (584, 'Mazda', 'B-Series', 48935);
insert into vehicle (id, make, model, price) values (585, 'Ford', 'F150', 18702);
insert into vehicle (id, make, model, price) values (586, 'Mercedes-Benz', '300SD', 30231);
insert into vehicle (id, make, model, price) values (587, 'Subaru', 'Impreza', 10852);
insert into vehicle (id, make, model, price) values (588, 'Mitsubishi', 'Truck', 70843);
insert into vehicle (id, make, model, price) values (589, 'Chevrolet', 'Express', 58711);
insert into vehicle (id, make, model, price) values (590, 'Lincoln', 'MKS', 87829);
insert into vehicle (id, make, model, price) values (591, 'Dodge', 'Ram 1500 Club', 90386);
insert into vehicle (id, make, model, price) values (592, 'Mazda', 'B-Series', 77262);
insert into vehicle (id, make, model, price) values (593, 'Ford', 'Tempo', 61855);
insert into vehicle (id, make, model, price) values (594, 'Volvo', 'XC60', 84595);
insert into vehicle (id, make, model, price) values (595, 'Audi', 'TT', 83467);
insert into vehicle (id, make, model, price) values (596, 'Subaru', 'SVX', 60853);
insert into vehicle (id, make, model, price) values (597, 'BMW', 'Z3', 59845);
insert into vehicle (id, make, model, price) values (598, 'Volkswagen', 'GTI', 27988);
insert into vehicle (id, make, model, price) values (599, 'Ford', 'Explorer Sport', 47676);
insert into vehicle (id, make, model, price) values (600, 'Nissan', 'Altima', 73774);
insert into vehicle (id, make, model, price) values (601, 'Volkswagen', 'Golf', 92307);
insert into vehicle (id, make, model, price) values (602, 'Chevrolet', 'Venture', 23923);
insert into vehicle (id, make, model, price) values (603, 'Chevrolet', 'Tahoe', 52334);
insert into vehicle (id, make, model, price) values (604, 'Ford', 'F250', 48945);
insert into vehicle (id, make, model, price) values (605, 'Mazda', 'Protege', 11703);
insert into vehicle (id, make, model, price) values (606, 'Lincoln', 'Town Car', 72307);
insert into vehicle (id, make, model, price) values (607, 'Volkswagen', 'Passat', 72486);
insert into vehicle (id, make, model, price) values (608, 'Toyota', 'RAV4', 49038);
insert into vehicle (id, make, model, price) values (609, 'Ford', 'Mustang', 30372);
insert into vehicle (id, make, model, price) values (610, 'Isuzu', 'Amigo', 55410);
insert into vehicle (id, make, model, price) values (611, 'Dodge', 'Ram 2500', 46692);
insert into vehicle (id, make, model, price) values (612, 'Mitsubishi', '3000GT', 44871);
insert into vehicle (id, make, model, price) values (613, 'Lincoln', 'Town Car', 93597);
insert into vehicle (id, make, model, price) values (614, 'Pontiac', 'Bonneville', 70299);
insert into vehicle (id, make, model, price) values (615, 'Mazda', 'Tribute', 84814);
insert into vehicle (id, make, model, price) values (616, 'Hyundai', 'Elantra', 28197);
insert into vehicle (id, make, model, price) values (617, 'Honda', 'CR-Z', 22409);
insert into vehicle (id, make, model, price) values (618, 'Porsche', 'Boxster', 58000);
insert into vehicle (id, make, model, price) values (619, 'Chevrolet', 'Malibu', 92542);
insert into vehicle (id, make, model, price) values (620, 'Mercury', 'Mountaineer', 77179);
insert into vehicle (id, make, model, price) values (621, 'Suzuki', 'Daewoo Lacetti', 55227);
insert into vehicle (id, make, model, price) values (622, 'Ford', 'Taurus', 11425);
insert into vehicle (id, make, model, price) values (623, 'Saturn', 'Aura', 71671);
insert into vehicle (id, make, model, price) values (624, 'Mercedes-Benz', 'E-Class', 80012);
insert into vehicle (id, make, model, price) values (625, 'Porsche', 'Cayenne', 74046);
insert into vehicle (id, make, model, price) values (626, 'Land Rover', 'Range Rover Classic', 25844);
insert into vehicle (id, make, model, price) values (627, 'Nissan', 'Sentra', 60136);
insert into vehicle (id, make, model, price) values (628, 'Isuzu', 'Rodeo', 90521);
insert into vehicle (id, make, model, price) values (629, 'Volkswagen', 'New Beetle', 71729);
insert into vehicle (id, make, model, price) values (630, 'Chrysler', 'Sebring', 52111);
insert into vehicle (id, make, model, price) values (631, 'Hyundai', 'Azera', 54052);
insert into vehicle (id, make, model, price) values (632, 'Mazda', 'Protege', 60244);
insert into vehicle (id, make, model, price) values (633, 'Jaguar', 'S-Type', 66905);
insert into vehicle (id, make, model, price) values (634, 'Mitsubishi', 'Endeavor', 83352);
insert into vehicle (id, make, model, price) values (635, 'Bentley', 'Mulsanne', 98778);
insert into vehicle (id, make, model, price) values (636, 'Buick', 'Electra', 81814);
insert into vehicle (id, make, model, price) values (637, 'Mercedes-Benz', 'E-Class', 29016);
insert into vehicle (id, make, model, price) values (638, 'Pontiac', 'Firebird', 46157);
insert into vehicle (id, make, model, price) values (639, 'Hyundai', 'Elantra', 53161);
insert into vehicle (id, make, model, price) values (640, 'Chevrolet', '3500', 90658);
insert into vehicle (id, make, model, price) values (641, 'Mitsubishi', 'Pajero', 14908);
insert into vehicle (id, make, model, price) values (642, 'Chevrolet', 'Sportvan G30', 69045);
insert into vehicle (id, make, model, price) values (643, 'Mercedes-Benz', 'S-Class', 81238);
insert into vehicle (id, make, model, price) values (644, 'Mazda', 'MPV', 42691);
insert into vehicle (id, make, model, price) values (645, 'Ford', 'Escort', 33936);
insert into vehicle (id, make, model, price) values (646, 'Toyota', 'Land Cruiser', 55997);
insert into vehicle (id, make, model, price) values (647, 'BMW', 'X5', 95505);
insert into vehicle (id, make, model, price) values (648, 'Jeep', 'Liberty', 93230);
insert into vehicle (id, make, model, price) values (649, 'Mazda', 'Millenia', 64051);
insert into vehicle (id, make, model, price) values (650, 'Toyota', 'Highlander', 25164);
insert into vehicle (id, make, model, price) values (651, 'Lamborghini', 'Aventador', 58090);
insert into vehicle (id, make, model, price) values (652, 'Lexus', 'GX', 12961);
insert into vehicle (id, make, model, price) values (653, 'Dodge', 'Dakota Club', 82925);
insert into vehicle (id, make, model, price) values (654, 'BMW', 'M3', 35346);
insert into vehicle (id, make, model, price) values (655, 'Pontiac', 'G6', 59822);
insert into vehicle (id, make, model, price) values (656, 'BMW', '745', 71197);
insert into vehicle (id, make, model, price) values (657, 'Maserati', 'GranTurismo', 48920);
insert into vehicle (id, make, model, price) values (658, 'Chevrolet', 'Corsica', 79059);
insert into vehicle (id, make, model, price) values (659, 'Mitsubishi', 'GTO', 29759);
insert into vehicle (id, make, model, price) values (660, 'Ford', 'Crown Victoria', 25820);
insert into vehicle (id, make, model, price) values (661, 'Mercury', 'Sable', 41744);
insert into vehicle (id, make, model, price) values (662, 'Mazda', 'B-Series Plus', 36267);
insert into vehicle (id, make, model, price) values (663, 'Mazda', 'Mazdaspeed6', 37055);
insert into vehicle (id, make, model, price) values (664, 'Chrysler', 'Voyager', 28764);
insert into vehicle (id, make, model, price) values (665, 'Land Rover', 'Range Rover Sport', 37344);
insert into vehicle (id, make, model, price) values (666, 'Smart', 'Fortwo', 36918);
insert into vehicle (id, make, model, price) values (667, 'Saturn', 'S-Series', 99846);
insert into vehicle (id, make, model, price) values (668, 'Nissan', 'Quest', 86066);
insert into vehicle (id, make, model, price) values (669, 'Land Rover', 'Discovery', 85058);
insert into vehicle (id, make, model, price) values (670, 'GMC', 'Suburban 2500', 90935);
insert into vehicle (id, make, model, price) values (671, 'Dodge', 'Neon', 66311);
insert into vehicle (id, make, model, price) values (672, 'Mercedes-Benz', 'SL65 AMG', 58879);
insert into vehicle (id, make, model, price) values (673, 'Nissan', 'Pathfinder', 52877);
insert into vehicle (id, make, model, price) values (674, 'GMC', 'Sierra 2500', 95277);
insert into vehicle (id, make, model, price) values (675, 'Buick', 'Roadmaster', 79363);
insert into vehicle (id, make, model, price) values (676, 'Acura', 'RL', 23989);
insert into vehicle (id, make, model, price) values (677, 'Jeep', 'Grand Cherokee', 50446);
insert into vehicle (id, make, model, price) values (678, 'Volkswagen', 'Passat', 56394);
insert into vehicle (id, make, model, price) values (679, 'BMW', 'Z8', 14879);
insert into vehicle (id, make, model, price) values (680, 'Mazda', '626', 76418);
insert into vehicle (id, make, model, price) values (681, 'Lamborghini', 'Countach', 85001);
insert into vehicle (id, make, model, price) values (682, 'Kia', 'Rio', 64335);
insert into vehicle (id, make, model, price) values (683, 'Maserati', 'Karif', 72229);
insert into vehicle (id, make, model, price) values (684, 'Toyota', 'Tacoma', 12068);
insert into vehicle (id, make, model, price) values (685, 'Toyota', 'Celica', 57253);
insert into vehicle (id, make, model, price) values (686, 'Honda', 'Accord', 67674);
insert into vehicle (id, make, model, price) values (687, 'Dodge', 'Ram Van 1500', 12958);
insert into vehicle (id, make, model, price) values (688, 'Pontiac', 'Bonneville', 86574);
insert into vehicle (id, make, model, price) values (689, 'Porsche', '911', 88338);
insert into vehicle (id, make, model, price) values (690, 'Honda', 'Ridgeline', 58049);
insert into vehicle (id, make, model, price) values (691, 'Audi', 'S4', 93400);
insert into vehicle (id, make, model, price) values (692, 'Mitsubishi', 'Montero', 28404);
insert into vehicle (id, make, model, price) values (693, 'Jaguar', 'S-Type', 52139);
insert into vehicle (id, make, model, price) values (694, 'Chevrolet', 'Suburban 1500', 80240);
insert into vehicle (id, make, model, price) values (695, 'Mercury', 'Tracer', 30365);
insert into vehicle (id, make, model, price) values (696, 'Chevrolet', 'Avalanche', 75316);
insert into vehicle (id, make, model, price) values (697, 'Oldsmobile', 'Bravada', 99747);
insert into vehicle (id, make, model, price) values (698, 'Porsche', '928', 49720);
insert into vehicle (id, make, model, price) values (699, 'Mitsubishi', 'Galant', 70436);
insert into vehicle (id, make, model, price) values (700, 'Mercury', 'Tracer', 62935);
insert into vehicle (id, make, model, price) values (701, 'BMW', 'M3', 48990);
insert into vehicle (id, make, model, price) values (702, 'Mercury', 'Sable', 72278);
insert into vehicle (id, make, model, price) values (703, 'Chevrolet', 'Impala', 73841);
insert into vehicle (id, make, model, price) values (704, 'Audi', 'S5', 30456);
insert into vehicle (id, make, model, price) values (705, 'GMC', 'Jimmy', 85926);
insert into vehicle (id, make, model, price) values (706, 'Pontiac', 'Sunfire', 17424);
insert into vehicle (id, make, model, price) values (707, 'Ford', 'Galaxie', 96996);
insert into vehicle (id, make, model, price) values (708, 'Dodge', 'Ram 2500', 55029);
insert into vehicle (id, make, model, price) values (709, 'Volkswagen', 'Type 2', 72160);
insert into vehicle (id, make, model, price) values (710, 'Lotus', 'Exige', 57439);
insert into vehicle (id, make, model, price) values (711, 'Toyota', 'Tacoma Xtra', 97516);
insert into vehicle (id, make, model, price) values (712, 'Mitsubishi', 'Precis', 78082);
insert into vehicle (id, make, model, price) values (713, 'Mazda', 'CX-7', 31583);
insert into vehicle (id, make, model, price) values (714, 'Oldsmobile', 'Aurora', 25666);
insert into vehicle (id, make, model, price) values (715, 'Ford', 'F-Series', 48276);
insert into vehicle (id, make, model, price) values (716, 'Buick', 'Regal', 90713);
insert into vehicle (id, make, model, price) values (717, 'Daewoo', 'Leganza', 97687);
insert into vehicle (id, make, model, price) values (718, 'Pontiac', 'Aztek', 28693);
insert into vehicle (id, make, model, price) values (719, 'Lincoln', 'Continental', 51070);
insert into vehicle (id, make, model, price) values (720, 'Jaguar', 'XK Series', 49518);
insert into vehicle (id, make, model, price) values (721, 'Cadillac', 'CTS-V', 89339);
insert into vehicle (id, make, model, price) values (722, 'Mercedes-Benz', 'R-Class', 18636);
insert into vehicle (id, make, model, price) values (723, 'Volkswagen', 'CC', 71781);
insert into vehicle (id, make, model, price) values (724, 'Pontiac', 'Fiero', 76546);
insert into vehicle (id, make, model, price) values (725, 'Buick', 'Roadmaster', 43012);
insert into vehicle (id, make, model, price) values (726, 'Chrysler', '300', 50643);
insert into vehicle (id, make, model, price) values (727, 'Lexus', 'RX Hybrid', 87515);
insert into vehicle (id, make, model, price) values (728, 'Volvo', 'S80', 59000);
insert into vehicle (id, make, model, price) values (729, 'Aston Martin', 'Vantage', 38527);
insert into vehicle (id, make, model, price) values (730, 'Maserati', 'Quattroporte', 38064);
insert into vehicle (id, make, model, price) values (731, 'Pontiac', 'Grand Prix', 55572);
insert into vehicle (id, make, model, price) values (732, 'GMC', 'Suburban 1500', 14495);
insert into vehicle (id, make, model, price) values (733, 'Maserati', 'Quattroporte', 46714);
insert into vehicle (id, make, model, price) values (734, 'Volkswagen', 'GTI', 63801);
insert into vehicle (id, make, model, price) values (735, 'Hyundai', 'Sonata', 30240);
insert into vehicle (id, make, model, price) values (736, 'Dodge', 'Dakota Club', 53648);
insert into vehicle (id, make, model, price) values (737, 'Toyota', 'Corolla', 73397);
insert into vehicle (id, make, model, price) values (738, 'Chevrolet', 'Sportvan G20', 11212);
insert into vehicle (id, make, model, price) values (739, 'Ford', 'Explorer Sport', 82647);
insert into vehicle (id, make, model, price) values (740, 'Lexus', 'ES', 44991);
insert into vehicle (id, make, model, price) values (741, 'Dodge', 'Viper', 20423);
insert into vehicle (id, make, model, price) values (742, 'Subaru', 'Forester', 77025);
insert into vehicle (id, make, model, price) values (743, 'Volkswagen', 'GTI', 40568);
insert into vehicle (id, make, model, price) values (744, 'Mercedes-Benz', 'E-Class', 14460);
insert into vehicle (id, make, model, price) values (745, 'Nissan', 'Pathfinder', 66399);
insert into vehicle (id, make, model, price) values (746, 'Bentley', 'Continental GTC', 85141);
insert into vehicle (id, make, model, price) values (747, 'Chevrolet', 'Corvette', 89976);
insert into vehicle (id, make, model, price) values (748, 'Mitsubishi', 'GTO', 75495);
insert into vehicle (id, make, model, price) values (749, 'Chevrolet', 'LUV', 64180);
insert into vehicle (id, make, model, price) values (750, 'Saab', '9-7X', 39705);
insert into vehicle (id, make, model, price) values (751, 'Mazda', 'RX-7', 43567);
insert into vehicle (id, make, model, price) values (752, 'Ford', 'Mustang', 95235);
insert into vehicle (id, make, model, price) values (753, 'Mercedes-Benz', 'SLK-Class', 84595);
insert into vehicle (id, make, model, price) values (754, 'Toyota', 'Camry', 38301);
insert into vehicle (id, make, model, price) values (755, 'Hyundai', 'Santa Fe', 90337);
insert into vehicle (id, make, model, price) values (756, 'Volvo', 'S60', 80733);
insert into vehicle (id, make, model, price) values (757, 'Volkswagen', 'Rabbit', 36689);
insert into vehicle (id, make, model, price) values (758, 'Lamborghini', 'Murciélago', 41012);
insert into vehicle (id, make, model, price) values (759, 'Jaguar', 'XJ', 99276);
insert into vehicle (id, make, model, price) values (760, 'Eagle', 'Vision', 51592);
insert into vehicle (id, make, model, price) values (761, 'Ford', 'Ranger', 37683);
insert into vehicle (id, make, model, price) values (762, 'Infiniti', 'G35', 77636);
insert into vehicle (id, make, model, price) values (763, 'Mitsubishi', '3000GT', 82276);
insert into vehicle (id, make, model, price) values (764, 'Toyota', 'Camry', 50776);
insert into vehicle (id, make, model, price) values (765, 'Subaru', 'Legacy', 99546);
insert into vehicle (id, make, model, price) values (766, 'Chrysler', 'Concorde', 94772);
insert into vehicle (id, make, model, price) values (767, 'Oldsmobile', 'Silhouette', 44709);
insert into vehicle (id, make, model, price) values (768, 'Mercedes-Benz', 'C-Class', 45278);
insert into vehicle (id, make, model, price) values (769, 'Plymouth', 'Prowler', 96305);
insert into vehicle (id, make, model, price) values (770, 'Dodge', 'Ram 1500', 69462);
insert into vehicle (id, make, model, price) values (771, 'Chevrolet', 'Silverado 2500', 26316);
insert into vehicle (id, make, model, price) values (772, 'Scion', 'tC', 90436);
insert into vehicle (id, make, model, price) values (773, 'Lamborghini', 'Gallardo', 96169);
insert into vehicle (id, make, model, price) values (774, 'Pontiac', 'Firebird Formula', 69399);
insert into vehicle (id, make, model, price) values (775, 'Porsche', 'Boxster', 21195);
insert into vehicle (id, make, model, price) values (776, 'Chrysler', 'LHS', 86148);
insert into vehicle (id, make, model, price) values (777, 'Mercedes-Benz', 'E-Class', 21898);
insert into vehicle (id, make, model, price) values (778, 'Volkswagen', 'Jetta', 22695);
insert into vehicle (id, make, model, price) values (779, 'Ford', 'Explorer Sport', 54833);
insert into vehicle (id, make, model, price) values (780, 'Acura', 'RL', 17232);
insert into vehicle (id, make, model, price) values (781, 'Kia', 'Sportage', 64622);
insert into vehicle (id, make, model, price) values (782, 'Honda', 'Accord', 24518);
insert into vehicle (id, make, model, price) values (783, 'Chrysler', '300', 47873);
insert into vehicle (id, make, model, price) values (784, 'Peugeot', '207', 90373);
insert into vehicle (id, make, model, price) values (785, 'Dodge', 'Nitro', 79786);
insert into vehicle (id, make, model, price) values (786, 'Chrysler', '300', 62123);
insert into vehicle (id, make, model, price) values (787, 'Kia', 'Sephia', 89061);
insert into vehicle (id, make, model, price) values (788, 'Mercury', 'Grand Marquis', 86784);
insert into vehicle (id, make, model, price) values (789, 'Lexus', 'RX', 66977);
insert into vehicle (id, make, model, price) values (790, 'Honda', 'Odyssey', 14687);
insert into vehicle (id, make, model, price) values (791, 'BMW', '5 Series', 21400);
insert into vehicle (id, make, model, price) values (792, 'Jaguar', 'XF', 24644);
insert into vehicle (id, make, model, price) values (793, 'Mazda', 'Mazda3', 25795);
insert into vehicle (id, make, model, price) values (794, 'Infiniti', 'Q', 25479);
insert into vehicle (id, make, model, price) values (795, 'Mazda', 'MX-5', 14364);
insert into vehicle (id, make, model, price) values (796, 'Mazda', 'MPV', 12746);
insert into vehicle (id, make, model, price) values (797, 'Hyundai', 'Sonata', 67835);
insert into vehicle (id, make, model, price) values (798, 'Honda', 'Odyssey', 77989);
insert into vehicle (id, make, model, price) values (799, 'Honda', 'Odyssey', 15721);
insert into vehicle (id, make, model, price) values (800, 'Hyundai', 'Azera', 78982);
insert into vehicle (id, make, model, price) values (801, 'Mercury', 'Capri', 72452);
insert into vehicle (id, make, model, price) values (802, 'Oldsmobile', '98', 12509);
insert into vehicle (id, make, model, price) values (803, 'Suzuki', 'SJ', 80098);
insert into vehicle (id, make, model, price) values (804, 'Chevrolet', 'Express 3500', 57636);
insert into vehicle (id, make, model, price) values (805, 'Ford', 'Windstar', 42875);
insert into vehicle (id, make, model, price) values (806, 'BMW', '3 Series', 44726);
insert into vehicle (id, make, model, price) values (807, 'Lincoln', 'Town Car', 95515);
insert into vehicle (id, make, model, price) values (808, 'Ford', 'Excursion', 97326);
insert into vehicle (id, make, model, price) values (809, 'Scion', 'FR-S', 83043);
insert into vehicle (id, make, model, price) values (810, 'BMW', 'Z8', 94196);
insert into vehicle (id, make, model, price) values (811, 'Mazda', 'Protege', 92177);
insert into vehicle (id, make, model, price) values (812, 'Volkswagen', 'Golf', 98284);
insert into vehicle (id, make, model, price) values (813, 'GMC', 'Yukon', 72201);
insert into vehicle (id, make, model, price) values (814, 'Kia', 'Sedona', 15302);
insert into vehicle (id, make, model, price) values (815, 'Mercury', 'Topaz', 81782);
insert into vehicle (id, make, model, price) values (816, 'Nissan', 'Cube', 84078);
insert into vehicle (id, make, model, price) values (817, 'Chevrolet', 'Impala', 36395);
insert into vehicle (id, make, model, price) values (818, 'Ford', 'Expedition', 23441);
insert into vehicle (id, make, model, price) values (819, 'Nissan', '300ZX', 50900);
insert into vehicle (id, make, model, price) values (820, 'Pontiac', 'Grand Prix', 81225);
insert into vehicle (id, make, model, price) values (821, 'Isuzu', 'Ascender', 36502);
insert into vehicle (id, make, model, price) values (822, 'Volvo', 'XC70', 99271);
insert into vehicle (id, make, model, price) values (823, 'Chevrolet', 'Corvette', 37207);
insert into vehicle (id, make, model, price) values (824, 'Mitsubishi', 'Galant', 24096);
insert into vehicle (id, make, model, price) values (825, 'Ford', 'F-Series', 43230);
insert into vehicle (id, make, model, price) values (826, 'Saturn', 'S-Series', 86878);
insert into vehicle (id, make, model, price) values (827, 'Cadillac', 'Catera', 32930);
insert into vehicle (id, make, model, price) values (828, 'Hummer', 'H2', 23438);
insert into vehicle (id, make, model, price) values (829, 'Land Rover', 'Discovery Series II', 52240);
insert into vehicle (id, make, model, price) values (830, 'Mazda', 'B-Series Plus', 47386);
insert into vehicle (id, make, model, price) values (831, 'Pontiac', 'Grand Am', 18950);
insert into vehicle (id, make, model, price) values (832, 'Maybach', '62', 70480);
insert into vehicle (id, make, model, price) values (833, 'Mercedes-Benz', 'SLR McLaren', 58991);
insert into vehicle (id, make, model, price) values (834, 'Lexus', 'LS', 76205);
insert into vehicle (id, make, model, price) values (835, 'Chrysler', 'Pacifica', 44743);
insert into vehicle (id, make, model, price) values (836, 'BMW', '8 Series', 89888);
insert into vehicle (id, make, model, price) values (837, 'Mercedes-Benz', '300D', 94503);
insert into vehicle (id, make, model, price) values (838, 'Ford', 'Econoline E350', 45991);
insert into vehicle (id, make, model, price) values (839, 'Scion', 'xD', 24727);
insert into vehicle (id, make, model, price) values (840, 'Hyundai', 'Accent', 23579);
insert into vehicle (id, make, model, price) values (841, 'Ford', 'Windstar', 91281);
insert into vehicle (id, make, model, price) values (842, 'Acura', 'Integra', 12460);
insert into vehicle (id, make, model, price) values (843, 'BMW', '3 Series', 68415);
insert into vehicle (id, make, model, price) values (844, 'Dodge', 'Grand Caravan', 28035);
insert into vehicle (id, make, model, price) values (845, 'Chevrolet', 'Suburban 1500', 95491);
insert into vehicle (id, make, model, price) values (846, 'Cadillac', 'Escalade ESV', 15647);
insert into vehicle (id, make, model, price) values (847, 'Ford', 'Laser', 87365);
insert into vehicle (id, make, model, price) values (848, 'Hummer', 'H3', 51673);
insert into vehicle (id, make, model, price) values (849, 'Lexus', 'GS', 40097);
insert into vehicle (id, make, model, price) values (850, 'Chevrolet', 'Colorado', 77078);
insert into vehicle (id, make, model, price) values (851, 'Toyota', '4Runner', 33811);
insert into vehicle (id, make, model, price) values (852, 'Mercury', 'Sable', 38671);
insert into vehicle (id, make, model, price) values (853, 'Ford', 'Econoline E250', 63221);
insert into vehicle (id, make, model, price) values (854, 'BMW', '3 Series', 79638);
insert into vehicle (id, make, model, price) values (855, 'Dodge', 'Ram 3500 Club', 91066);
insert into vehicle (id, make, model, price) values (856, 'GMC', 'Jimmy', 85805);
insert into vehicle (id, make, model, price) values (857, 'Chrysler', '300M', 75383);
insert into vehicle (id, make, model, price) values (858, 'Geo', 'Tracker', 57839);
insert into vehicle (id, make, model, price) values (859, 'Acura', 'CL', 64439);
insert into vehicle (id, make, model, price) values (860, 'Jaguar', 'XJ Series', 99192);
insert into vehicle (id, make, model, price) values (861, 'Volkswagen', 'Jetta', 18926);
insert into vehicle (id, make, model, price) values (862, 'Mitsubishi', 'Diamante', 56557);
insert into vehicle (id, make, model, price) values (863, 'Lamborghini', 'Murciélago', 78398);
insert into vehicle (id, make, model, price) values (864, 'Volkswagen', 'Golf III', 25143);
insert into vehicle (id, make, model, price) values (865, 'Chevrolet', 'Express 3500', 23162);
insert into vehicle (id, make, model, price) values (866, 'Chevrolet', 'Suburban 1500', 14523);
insert into vehicle (id, make, model, price) values (867, 'GMC', 'Sierra 3500', 25900);
insert into vehicle (id, make, model, price) values (868, 'Chevrolet', 'Express 3500', 98577);
insert into vehicle (id, make, model, price) values (869, 'Ford', 'Econoline E350', 85326);
insert into vehicle (id, make, model, price) values (870, 'Chevrolet', 'Sportvan G20', 94906);
insert into vehicle (id, make, model, price) values (871, 'Mazda', 'CX-7', 44172);
insert into vehicle (id, make, model, price) values (872, 'Nissan', 'Quest', 78117);
insert into vehicle (id, make, model, price) values (873, 'Suzuki', 'Swift', 62445);
insert into vehicle (id, make, model, price) values (874, 'Hummer', 'H2', 38095);
insert into vehicle (id, make, model, price) values (875, 'Chevrolet', 'Cruze', 42597);
insert into vehicle (id, make, model, price) values (876, 'Dodge', 'D350 Club', 76149);
insert into vehicle (id, make, model, price) values (877, 'Dodge', 'Daytona', 17434);
insert into vehicle (id, make, model, price) values (878, 'Jaguar', 'S-Type', 59084);
insert into vehicle (id, make, model, price) values (879, 'Honda', 'CR-Z', 74177);
insert into vehicle (id, make, model, price) values (880, 'Mercury', 'Grand Marquis', 45268);
insert into vehicle (id, make, model, price) values (881, 'Maybach', 'Landaulet', 73431);
insert into vehicle (id, make, model, price) values (882, 'Volkswagen', 'Passat', 51560);
insert into vehicle (id, make, model, price) values (883, 'Mazda', 'MX-5', 85975);
insert into vehicle (id, make, model, price) values (884, 'Dodge', 'Ram 1500', 78394);
insert into vehicle (id, make, model, price) values (885, 'Suzuki', 'Sidekick', 41992);
insert into vehicle (id, make, model, price) values (886, 'Volkswagen', 'Golf III', 99371);
insert into vehicle (id, make, model, price) values (887, 'Chevrolet', 'Cruze', 12332);
insert into vehicle (id, make, model, price) values (888, 'GMC', 'Sonoma', 71148);
insert into vehicle (id, make, model, price) values (889, 'Chevrolet', 'Silverado 2500', 65746);
insert into vehicle (id, make, model, price) values (890, 'Volvo', 'V40', 45544);
insert into vehicle (id, make, model, price) values (891, 'Mercedes-Benz', 'CLK-Class', 76550);
insert into vehicle (id, make, model, price) values (892, 'Acura', 'TL', 89341);
insert into vehicle (id, make, model, price) values (893, 'Chevrolet', 'S10', 46074);
insert into vehicle (id, make, model, price) values (894, 'Mitsubishi', 'Diamante', 67341);
insert into vehicle (id, make, model, price) values (895, 'Subaru', 'Impreza', 33549);
insert into vehicle (id, make, model, price) values (896, 'Dodge', 'Ram 3500', 41484);
insert into vehicle (id, make, model, price) values (897, 'Saturn', 'VUE', 98812);
insert into vehicle (id, make, model, price) values (898, 'Suzuki', 'Esteem', 90146);
insert into vehicle (id, make, model, price) values (899, 'Lotus', 'Exige', 72446);
insert into vehicle (id, make, model, price) values (900, 'Dodge', 'Ram 1500 Club', 35271);
insert into vehicle (id, make, model, price) values (901, 'Isuzu', 'Trooper', 67311);
insert into vehicle (id, make, model, price) values (902, 'Toyota', 'Prius v', 97126);
insert into vehicle (id, make, model, price) values (903, 'Ford', 'Explorer', 93737);
insert into vehicle (id, make, model, price) values (904, 'Mazda', 'Tribute', 36420);
insert into vehicle (id, make, model, price) values (905, 'Bentley', 'Continental Flying Spur', 35276);
insert into vehicle (id, make, model, price) values (906, 'Ford', 'E250', 88132);
insert into vehicle (id, make, model, price) values (907, 'Mitsubishi', 'Mirage', 24470);
insert into vehicle (id, make, model, price) values (908, 'Chevrolet', 'Aveo', 97003);
insert into vehicle (id, make, model, price) values (909, 'Honda', 'Passport', 54632);
insert into vehicle (id, make, model, price) values (910, 'Mercury', 'Mountaineer', 42721);
insert into vehicle (id, make, model, price) values (911, 'Scion', 'tC', 70005);
insert into vehicle (id, make, model, price) values (912, 'Mercedes-Benz', 'SLR McLaren', 45604);
insert into vehicle (id, make, model, price) values (913, 'Mazda', 'B-Series Plus', 31805);
insert into vehicle (id, make, model, price) values (914, 'Dodge', 'Viper', 85806);
insert into vehicle (id, make, model, price) values (915, 'Volkswagen', 'Jetta', 50843);
insert into vehicle (id, make, model, price) values (916, 'Toyota', 'TundraMax', 76918);
insert into vehicle (id, make, model, price) values (917, 'Oldsmobile', 'Cutlass Supreme', 15047);
insert into vehicle (id, make, model, price) values (918, 'Audi', 'TT', 18103);
insert into vehicle (id, make, model, price) values (919, 'Pontiac', 'Firebird', 78919);
insert into vehicle (id, make, model, price) values (920, 'MINI', 'Cooper Clubman', 49404);
insert into vehicle (id, make, model, price) values (921, 'Suzuki', 'Grand Vitara', 36057);
insert into vehicle (id, make, model, price) values (922, 'Oldsmobile', 'Cutlass Supreme', 83214);
insert into vehicle (id, make, model, price) values (923, 'Toyota', 'Xtra', 47613);
insert into vehicle (id, make, model, price) values (924, 'Lexus', 'GX', 12068);
insert into vehicle (id, make, model, price) values (925, 'Toyota', 'Celica', 53397);
insert into vehicle (id, make, model, price) values (926, 'Volkswagen', 'Passat', 16320);
insert into vehicle (id, make, model, price) values (927, 'Bentley', 'Continental GT', 85483);
insert into vehicle (id, make, model, price) values (928, 'Ford', 'E-Series', 39121);
insert into vehicle (id, make, model, price) values (929, 'Dodge', 'Stratus', 65352);
insert into vehicle (id, make, model, price) values (930, 'Mitsubishi', 'Mirage', 70216);
insert into vehicle (id, make, model, price) values (931, 'Mercury', 'Mountaineer', 50795);
insert into vehicle (id, make, model, price) values (932, 'BMW', '7 Series', 79288);
insert into vehicle (id, make, model, price) values (933, 'Lincoln', 'MKZ', 28686);
insert into vehicle (id, make, model, price) values (934, 'Mitsubishi', 'Challenger', 82360);
insert into vehicle (id, make, model, price) values (935, 'Nissan', 'Armada', 96482);
insert into vehicle (id, make, model, price) values (936, 'Audi', 'TT', 23066);
insert into vehicle (id, make, model, price) values (937, 'GMC', '2500', 96885);
insert into vehicle (id, make, model, price) values (938, 'Chevrolet', 'Corvette', 57876);
insert into vehicle (id, make, model, price) values (939, 'MINI', 'Clubman', 61253);
insert into vehicle (id, make, model, price) values (940, 'Saab', '9-5', 80272);
insert into vehicle (id, make, model, price) values (941, 'Lincoln', 'Navigator', 60026);
insert into vehicle (id, make, model, price) values (942, 'Mercedes-Benz', 'GL-Class', 51554);
insert into vehicle (id, make, model, price) values (943, 'Honda', 'Accord', 82359);
insert into vehicle (id, make, model, price) values (944, 'Ford', 'Escort', 30368);
insert into vehicle (id, make, model, price) values (945, 'Honda', 'Accord', 48024);
insert into vehicle (id, make, model, price) values (946, 'Ford', 'Mustang', 10766);
insert into vehicle (id, make, model, price) values (947, 'GMC', 'Sierra 2500', 64693);
insert into vehicle (id, make, model, price) values (948, 'Volkswagen', 'Fox', 33923);
insert into vehicle (id, make, model, price) values (949, 'Saab', '900', 17857);
insert into vehicle (id, make, model, price) values (950, 'Toyota', 'Land Cruiser', 41324);
insert into vehicle (id, make, model, price) values (951, 'Subaru', 'XT', 16920);
insert into vehicle (id, make, model, price) values (952, 'Buick', 'Century', 22862);
insert into vehicle (id, make, model, price) values (953, 'Land Rover', 'Range Rover', 38523);
insert into vehicle (id, make, model, price) values (954, 'Chevrolet', 'Suburban 1500', 15544);
insert into vehicle (id, make, model, price) values (955, 'Ford', 'F450', 62681);
insert into vehicle (id, make, model, price) values (956, 'Suzuki', 'Aerio', 98720);
insert into vehicle (id, make, model, price) values (957, 'Dodge', 'Ram 3500', 86094);
insert into vehicle (id, make, model, price) values (958, 'Mitsubishi', 'Endeavor', 24386);
insert into vehicle (id, make, model, price) values (959, 'GMC', 'Yukon', 76652);
insert into vehicle (id, make, model, price) values (960, 'Suzuki', 'Swift', 32573);
insert into vehicle (id, make, model, price) values (961, 'Nissan', 'Altima', 29171);
insert into vehicle (id, make, model, price) values (962, 'Ford', 'E-Series', 20141);
insert into vehicle (id, make, model, price) values (963, 'Mercedes-Benz', 'SL-Class', 13317);
insert into vehicle (id, make, model, price) values (964, 'Lotus', 'Elise', 47846);
insert into vehicle (id, make, model, price) values (965, 'Lamborghini', 'Gallardo', 75425);
insert into vehicle (id, make, model, price) values (966, 'Lexus', 'LX', 48270);
insert into vehicle (id, make, model, price) values (967, 'BMW', '7 Series', 63445);
insert into vehicle (id, make, model, price) values (968, 'Porsche', '911', 34715);
insert into vehicle (id, make, model, price) values (969, 'Pontiac', 'Aztek', 12538);
insert into vehicle (id, make, model, price) values (970, 'Ford', 'Econoline E250', 72013);
insert into vehicle (id, make, model, price) values (971, 'Mazda', 'Millenia', 24941);
insert into vehicle (id, make, model, price) values (972, 'Dodge', 'Ram 3500', 25339);
insert into vehicle (id, make, model, price) values (973, 'Toyota', 'Previa', 67153);
insert into vehicle (id, make, model, price) values (974, 'GMC', 'Sonoma', 44179);
insert into vehicle (id, make, model, price) values (975, 'Buick', 'LeSabre', 54149);
insert into vehicle (id, make, model, price) values (976, 'Dodge', 'Viper', 96620);
insert into vehicle (id, make, model, price) values (977, 'Mazda', 'Tribute', 27497);
insert into vehicle (id, make, model, price) values (978, 'Dodge', 'D350', 66495);
insert into vehicle (id, make, model, price) values (979, 'GMC', 'Sierra 1500', 10795);
insert into vehicle (id, make, model, price) values (980, 'Dodge', 'Dakota', 88968);
insert into vehicle (id, make, model, price) values (981, 'Toyota', 'RAV4', 26639);
insert into vehicle (id, make, model, price) values (982, 'Saturn', 'VUE', 86082);
insert into vehicle (id, make, model, price) values (983, 'Volvo', '850', 39140);
insert into vehicle (id, make, model, price) values (984, 'Plymouth', 'Laser', 84208);
insert into vehicle (id, make, model, price) values (985, 'GMC', '3500', 67411);
insert into vehicle (id, make, model, price) values (986, 'Cadillac', 'DeVille', 46700);
insert into vehicle (id, make, model, price) values (987, 'BMW', 'M3', 38210);
insert into vehicle (id, make, model, price) values (988, 'Volkswagen', 'R32', 21092);
insert into vehicle (id, make, model, price) values (989, 'Dodge', 'Intrepid', 25822);
insert into vehicle (id, make, model, price) values (990, 'Suzuki', 'SJ 410', 57663);
insert into vehicle (id, make, model, price) values (991, 'Dodge', 'Magnum', 13760);
insert into vehicle (id, make, model, price) values (992, 'Nissan', 'Sentra', 40856);
insert into vehicle (id, make, model, price) values (993, 'Mercedes-Benz', 'GLK-Class', 39872);
insert into vehicle (id, make, model, price) values (994, 'BMW', 'X5', 95840);
insert into vehicle (id, make, model, price) values (995, 'Toyota', 'Land Cruiser', 55787);
insert into vehicle (id, make, model, price) values (996, 'Nissan', 'Murano', 87941);
insert into vehicle (id, make, model, price) values (997, 'Chrysler', 'LHS', 14664);
insert into vehicle (id, make, model, price) values (998, 'Ford', 'E-Series', 65386);
insert into vehicle (id, make, model, price) values (999, 'Subaru', 'Justy', 82549);
insert into vehicle (id, make, model, price) values (1000, 'Mazda', '626', 29669);
